
# 恒天公众号
wechat:
  mp:
    appId: wx1b0723ab8a95d54a
    secret: 6036488697434073fe91ddee23f7ab67
    token: 2jo3qu4nt98234ut89
    aesKey:
  templateId: 7Nqm4Mgl-TZYdgi3S56SptjqBMh4XOe0etyVxHWcifI

upload:
  path: C:\ftp\fe\upload\