spring:
  profiles:
    active: common, common_dev, bs_dao, bs_dao_dev, bs_service, bs_service_dev, bs_controller, bs_controller_dev

#日志
logging:
  level:
    com.htcs.kehaoduo: debug
  path: c:/kehaoduo/logs/bs

server:
  context-path: /bs
  port: 8082
